discount_factor: 0.95
eps_decrement: 0.99
eps_minimum: 0.01
epsilon: 1.0
learning_rate: 5.0e-05
memory_size: 15000
min_memory: 3000
mlp_hidden_units: !!python/tuple
- 256
- 128
- 64
num_actions: 2
seed: 42
